### ISSUE TITLE
Azure tests failing

### ISSUE THREAD

**Issue by jordiferrero** [LumiSpy/lumispy#169] opened 2023-01-04 19:50 UTC
#### Describe the bug
Azure tests pipeline is failing, as discussed in #168. The error happens when it tries to import:
```
from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
##[error]Bash exited with code '1'.
```

#### To Reproduce
See [here ](https://dev.azure.com/Lumispy/lumispy/_build/results?buildId=764&view=logs&jobId=bd5e81e7-3dad-5701-f26e-86df05b1109f&j=bd5e81e7-3dad-5701-f26e-86df05b1109f&t=fcb8903f-5ee4-5a8b-81cb-29b501f6d590)for example.
```

#### Additional context
It seems it could be a problem caused by numpy 1.24 ([see here](https://github.com/numba/numba/issues/8615)).

#### What I already tried
I already tried and did not work:
- Set numpy < 1.24 during the installation (in requirement in `setup.py`)
- Remove all dependencies but only hyperspy 1.7

**Comment by ericpre** [comment] 2023-01-05 10:34
Indeed, this is related to numpy 1.24 and its incompatibility with numba. To be more precise, the issue is that numba (since version 0.54) has a "max pin" to numpy but a old version of numba without this pin is being installed along with the new version numpy. The dependency solver picks the "wrong" solution out of the two possible.

```
numba                     0.53.1           py38h8b71fd7_1    conda-forge
numcodecs                 0.11.0           py38h8dc9893_1    conda-forge
numexpr                   2.8.3           py38h36ff5c2_101    conda-forge
numpy                     1.24.1           py38hab0fcb9_0    conda-forge
```

<details><summary>Full environment</summary>
<p>

```
2023-01-04T19:23:49.0101859Z # packages in environment at /home/vsts/work/1/mambaforge/envs/test_env:
2023-01-04T19:23:49.0102275Z #
2023-01-04T19:23:49.0102589Z # Name                    Version                   Build  Channel
2023-01-04T19:23:49.0116125Z _libgcc_mutex             0.1                 conda_forge    conda-forge
2023-01-04T19:23:49.0116927Z _openmp_mutex             4.5                       2_gnu    conda-forge
2023-01-04T19:23:49.0117562Z aom                       3.5.0                h27087fc_0    conda-forge
2023-01-04T19:23:49.0118295Z appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
2023-01-04T19:23:49.0118826Z asciitree                 0.3.3                      py_2    conda-forge
2023-01-04T19:23:49.0119937Z asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0120590Z attrs                     22.2.0             pyh71513ae_0    conda-forge
2023-01-04T19:23:49.0121150Z backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
2023-01-04T19:23:49.0121686Z backports                 1.0                pyhd8ed1ab_3    conda-forge
2023-01-04T19:23:49.0122279Z backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0122879Z blosc                     1.21.3               hafa529b_0    conda-forge
2023-01-04T19:23:49.0123425Z brotli                    1.0.9                h166bdaf_8    conda-forge
2023-01-04T19:23:49.0124205Z brotli-bin                1.0.9                h166bdaf_8    conda-forge
2023-01-04T19:23:49.0124761Z brotlipy                  0.7.0           py38h0a891b7_1005    conda-forge
2023-01-04T19:23:49.0125320Z brunsli                   0.1                  h9c3ff4c_0    conda-forge
2023-01-04T19:23:49.0125847Z bzip2                     1.0.8                h7f98852_4    conda-forge
2023-01-04T19:23:49.0126412Z c-ares                    1.18.1               h7f98852_0    conda-forge
2023-01-04T19:23:49.0126947Z c-blosc2                  2.6.1                hf91038e_0    conda-forge
2023-01-04T19:23:49.0127514Z ca-certificates           2022.12.7            ha878542_0    conda-forge
2023-01-04T19:23:49.0128071Z cached-property           1.5.2                hd8ed1ab_1    conda-forge
2023-01-04T19:23:49.0128657Z cached_property           1.5.2              pyha770c72_1    conda-forge
2023-01-04T19:23:49.0129210Z certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0130768Z cffi                      1.15.1           py38h4a40e3a_3    conda-forge
2023-01-04T19:23:49.0131417Z cfitsio                   4.2.0                hd9d235c_0    conda-forge
2023-01-04T19:23:49.0131967Z charls                    2.3.4                h9c3ff4c_0    conda-forge
2023-01-04T19:23:49.0132514Z charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0133089Z click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
2023-01-04T19:23:49.0133636Z cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0134192Z colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0134725Z comm                      0.1.2              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0135568Z contourpy                 1.0.6            py38h43d8883_0    conda-forge
2023-01-04T19:23:49.0136116Z coverage                  7.0.3            py38h1de0b5d_0    conda-forge
2023-01-04T19:23:49.0136689Z cryptography              39.0.0           py38h3d167d9_0    conda-forge
2023-01-04T19:23:49.0137234Z cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0137790Z cytoolz                   0.12.0           py38h0a891b7_1    conda-forge
2023-01-04T19:23:49.0138355Z dask-core                 2022.12.1          pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0138895Z dav1d                     1.0.0                h166bdaf_1    conda-forge
2023-01-04T19:23:49.0139445Z debugpy                   1.6.4            py38hfa26641_0    conda-forge
2023-01-04T19:23:49.0139988Z decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0140532Z dill                      0.3.6              pyhd8ed1ab_1    conda-forge
2023-01-04T19:23:49.0141251Z entrypoints               0.4                pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0144341Z exceptiongroup            1.1.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0144784Z execnet                   1.9.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0145195Z executing                 1.2.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0145626Z fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0146045Z fonttools                 4.38.0           py38h0a891b7_1    conda-forge
2023-01-04T19:23:49.0146470Z freetype                  2.12.1               hca18f0e_1    conda-forge
2023-01-04T19:23:49.0146886Z fsspec                    2022.11.0          pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0147305Z giflib                    5.2.1                h36c2ea0_2    conda-forge
2023-01-04T19:23:49.0147703Z gmp                       6.2.1                h58526e2_0    conda-forge
2023-01-04T19:23:49.0148115Z gmpy2                     2.1.2            py38h793c122_1    conda-forge
2023-01-04T19:23:49.0148564Z h5py                      3.7.0           nompi_py38h7927eab_102    conda-forge
2023-01-04T19:23:49.0149000Z hdf5                      1.12.2          nompi_h4df4325_101    conda-forge
2023-01-04T19:23:49.0149446Z hyperspy-base             1.7.3            py38h0a891b7_0    conda-forge
2023-01-04T19:23:49.0149857Z idna                      3.4                pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0150292Z imagecodecs               2022.12.24       py38h7f61701_0    conda-forge
2023-01-04T19:23:49.0150716Z imageio                   2.23.0             pyhfa7a67d_0    conda-forge
2023-01-04T19:23:49.0151154Z importlib-metadata        6.0.0              pyha770c72_0    conda-forge
2023-01-04T19:23:49.0151583Z importlib_metadata        6.0.0                hd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0152019Z iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
2023-01-04T19:23:49.0152441Z ipykernel                 6.19.4             pyh210e3f2_0    conda-forge
2023-01-04T19:23:49.0152872Z ipyparallel               8.4.1              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0153286Z ipython                   8.8.0              pyh41d4057_0    conda-forge
2023-01-04T19:23:49.0153705Z jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0154109Z jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
2023-01-04T19:23:49.0154515Z jpeg                      9e                   h166bdaf_2    conda-forge
2023-01-04T19:23:49.0154920Z jupyter_client            7.4.8              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0155357Z jupyter_core              5.1.2            py38h578d9bd_0    conda-forge
2023-01-04T19:23:49.0155770Z jxrlib                    1.1                  h7f98852_2    conda-forge
2023-01-04T19:23:49.0156168Z keyutils                  1.6.1                h166bdaf_0    conda-forge
2023-01-04T19:23:49.0156707Z kiwisolver                1.4.4            py38h43d8883_1    conda-forge
2023-01-04T19:23:49.0157117Z krb5                      1.20.1               h81ceb04_0    conda-forge
2023-01-04T19:23:49.0157527Z lcms2                     2.14                 hfd0df8a_1    conda-forge
2023-01-04T19:23:49.0157935Z ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
2023-01-04T19:23:49.0158360Z lerc                      4.0.0                h27087fc_0    conda-forge
2023-01-04T19:23:49.0158756Z libaec                    1.0.6                h9c3ff4c_0    conda-forge
2023-01-04T19:23:49.0159170Z libavif                   0.11.1               h5cdd6b5_0    conda-forge
2023-01-04T19:23:49.0159590Z libblas                   3.9.0           16_linux64_openblas    conda-forge
2023-01-04T19:23:49.0160032Z libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
2023-01-04T19:23:49.0160789Z libbrotlidec              1.0.9                h166bdaf_8    conda-forge
2023-01-04T19:23:49.0161328Z libbrotlienc              1.0.9                h166bdaf_8    conda-forge
2023-01-04T19:23:49.0161756Z libcblas                  3.9.0           16_linux64_openblas    conda-forge
2023-01-04T19:23:49.0162188Z libcurl                   7.87.0               hdc1c0ab_0    conda-forge
2023-01-04T19:23:49.0162593Z libdeflate                1.14                 h166bdaf_0    conda-forge
2023-01-04T19:23:49.0163021Z libedit                   3.1.20191231         he28a2e2_2    conda-forge
2023-01-04T19:23:49.0163429Z libev                     4.33                 h516909a_1    conda-forge
2023-01-04T19:23:49.0163841Z libffi                    3.4.2                h7f98852_5    conda-forge
2023-01-04T19:23:49.0164250Z libgcc-ng                 12.2.0              h65d4601_19    conda-forge
2023-01-04T19:23:49.0164685Z libgfortran-ng            12.2.0              h69a702a_19    conda-forge
2023-01-04T19:23:49.0165108Z libgfortran5              12.2.0              h337968e_19    conda-forge
2023-01-04T19:23:49.0165531Z libgomp                   12.2.0              h65d4601_19    conda-forge
2023-01-04T19:23:49.0165960Z libjpeg-turbo             2.1.4                h166bdaf_0    conda-forge
2023-01-04T19:23:49.0166389Z liblapack                 3.9.0           16_linux64_openblas    conda-forge
2023-01-04T19:23:49.0166826Z libllvm10                 10.0.1               he513fc3_3    conda-forge
2023-01-04T19:23:49.0167240Z libnghttp2                1.51.0               hff17c54_0    conda-forge
2023-01-04T19:23:49.0167661Z libnsl                    2.0.0                h7f98852_0    conda-forge
2023-01-04T19:23:49.0168087Z libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
2023-01-04T19:23:49.0168526Z libpng                    1.6.39               h753d276_0    conda-forge
2023-01-04T19:23:49.0168933Z libsodium                 1.0.18               h36c2ea0_1    conda-forge
2023-01-04T19:23:49.0169361Z libsqlite                 3.40.0               h753d276_0    conda-forge
2023-01-04T19:23:49.0169780Z libssh2                   1.10.0               hf14f497_3    conda-forge
2023-01-04T19:23:49.0170209Z libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
2023-01-04T19:23:49.0170617Z libtiff                   4.5.0                h82bc61c_0    conda-forge
2023-01-04T19:23:49.0171039Z libuuid                   2.32.1            h7f98852_1000    conda-forge
2023-01-04T19:23:49.0171453Z libwebp-base              1.2.4                h166bdaf_0    conda-forge
2023-01-04T19:23:49.0171882Z libxcb                    1.13              h7f98852_1004    conda-forge
2023-01-04T19:23:49.0172287Z libzlib                   1.2.13               h166bdaf_4    conda-forge
2023-01-04T19:23:49.0172707Z libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
2023-01-04T19:23:49.0173120Z llvmlite                  0.36.0           py38h4630a5e_0    conda-forge
2023-01-04T19:23:49.0173532Z locket                    1.0.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0174021Z lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
2023-01-04T19:23:49.0174432Z markupsafe                2.1.1            py38h0a891b7_2    conda-forge
2023-01-04T19:23:49.0174876Z matplotlib-base           3.6.2            py38hb021067_0    conda-forge
2023-01-04T19:23:49.0175311Z matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0175744Z mpc                       1.2.1                h9f54685_0    conda-forge
2023-01-04T19:23:49.0176137Z mpfr                      4.1.0                h9202a9a_1    conda-forge
2023-01-04T19:23:49.0176551Z mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0176972Z msgpack-python            1.0.4            py38h43d8883_1    conda-forge
2023-01-04T19:23:49.0177406Z munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
2023-01-04T19:23:49.0177813Z natsort                   8.2.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0178299Z ncurses                   6.3                  h27087fc_1    conda-forge
2023-01-04T19:23:49.0178706Z nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0179137Z networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0179537Z nomkl                     1.0                  h5ca1d4c_0    conda-forge
2023-01-04T19:23:49.0179955Z numba                     0.53.1           py38h8b71fd7_1    conda-forge
2023-01-04T19:23:49.0180373Z numcodecs                 0.11.0           py38h8dc9893_1    conda-forge
2023-01-04T19:23:49.0180811Z numexpr                   2.8.3           py38h36ff5c2_101    conda-forge
2023-01-04T19:23:49.0181227Z numpy                     1.24.1           py38hab0fcb9_0    conda-forge
2023-01-04T19:23:49.0181633Z openjpeg                  2.5.0                hfec8fc6_2    conda-forge
2023-01-04T19:23:49.0182051Z openssl                   3.0.7                h0b41bf4_1    conda-forge
2023-01-04T19:23:49.0182460Z packaging                 22.0               pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0182881Z parso                     0.8.3              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0183280Z partd                     1.3.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0183736Z pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
2023-01-04T19:23:49.0184145Z pickleshare               0.7.5                   py_1003    conda-forge
2023-01-04T19:23:49.0184569Z pillow                    9.4.0            py38hb32c036_0    conda-forge
2023-01-04T19:23:49.0184974Z pint                      0.20.1             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0185386Z pip                       22.3.1             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0185792Z platformdirs              2.6.2              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0186217Z pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
2023-01-04T19:23:49.0186627Z pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0187052Z prettytable               3.5.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0187478Z prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
2023-01-04T19:23:49.0187912Z psutil                    5.9.4            py38h0a891b7_0    conda-forge
2023-01-04T19:23:49.0188334Z pthread-stubs             0.4               h36c2ea0_1001    conda-forge
2023-01-04T19:23:49.0188769Z ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
2023-01-04T19:23:49.0189184Z pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0189594Z pycparser                 2.21               pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0190021Z pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0190435Z pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0190942Z pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0191352Z pysocks                   1.7.1              pyha2e5f31_6    conda-forge
2023-01-04T19:23:49.0191773Z pytest                    7.2.0              pyhd8ed1ab_2    conda-forge
2023-01-04T19:23:49.0192181Z pytest-cov                4.0.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0192613Z pytest-faulthandler       2.0.1                      py_0    conda-forge
2023-01-04T19:23:49.0193031Z pytest-xdist              3.1.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0193475Z python                    3.8.15          h4a9ceb5_0_cpython    conda-forge
2023-01-04T19:23:49.0193906Z python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0194334Z python_abi                3.8                      3_cp38    conda-forge
2023-01-04T19:23:49.0194742Z pywavelets                1.3.0            py38h26c90d9_2    conda-forge
2023-01-04T19:23:49.0195239Z pyyaml                    6.0              py38h0a891b7_5    conda-forge
2023-01-04T19:23:49.0195648Z pyzmq                     24.0.1           py38hfc09fa9_1    conda-forge
2023-01-04T19:23:49.0196068Z readline                  8.1.2                h0f457ee_0    conda-forge
2023-01-04T19:23:49.0196477Z requests                  2.28.1             pyhd8ed1ab_1    conda-forge
2023-01-04T19:23:49.0196912Z scikit-image              0.19.3           py38h8f669ce_2    conda-forge
2023-01-04T19:23:49.0197336Z scipy                     1.10.0           py38h10c12cc_0    conda-forge
2023-01-04T19:23:49.0197750Z setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0198176Z six                       1.16.0             pyh6c4a22f_0    conda-forge
2023-01-04T19:23:49.0198576Z snappy                    1.1.9                hbd366e4_2    conda-forge
2023-01-04T19:23:49.0198995Z sparse                    0.13.0             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0199415Z stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0199844Z sympy                     1.11.1           py38h578d9bd_2    conda-forge
2023-01-04T19:23:49.0200356Z tifffile                  2022.10.10         pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0200788Z tk                        8.6.12               h27826a3_0    conda-forge
2023-01-04T19:23:49.0201181Z toml                      0.10.2             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0201600Z tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0202002Z toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0202424Z tornado                   6.2              py38h0a891b7_1    conda-forge
2023-01-04T19:23:49.0202829Z tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0203253Z traitlets                 5.8.0              pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0203674Z traits                    6.4.1            py38h0a891b7_1    conda-forge
2023-01-04T19:23:49.0204104Z typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0204536Z typing_extensions         4.4.0              pyha770c72_0    conda-forge
2023-01-04T19:23:49.0204985Z unicodedata2              15.0.0           py38h0a891b7_0    conda-forge
2023-01-04T19:23:49.0205408Z urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0205820Z wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
2023-01-04T19:23:49.0206240Z wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0206646Z xorg-libxau               1.0.9                h7f98852_0    conda-forge
2023-01-04T19:23:49.0207077Z xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
2023-01-04T19:23:49.0207479Z xz                        5.2.6                h166bdaf_0    conda-forge
2023-01-04T19:23:49.0207977Z yaml                      0.2.5                h7f98852_2    conda-forge
2023-01-04T19:23:49.0208376Z zarr                      2.13.3             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0208788Z zeromq                    4.3.4                h9c3ff4c_1    conda-forge
2023-01-04T19:23:49.0209185Z zfp                       1.0.0                h27087fc_3    conda-forge
2023-01-04T19:23:49.0209596Z zipp                      3.11.0             pyhd8ed1ab_0    conda-forge
2023-01-04T19:23:49.0209994Z zlib                      1.2.13               h166bdaf_4    conda-forge
2023-01-04T19:23:49.0210407Z zlib-ng                   2.0.6                h166bdaf_0    conda-forge
2023-01-04T19:23:49.0210805Z zstd                      1.5.2                h6239696_4    conda-forge
```

</p>
</details>

This can currently be reproduced with:
```
mamba install numpy numba
```
and it should be fixed by https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/376.

**Comment by ericpre** [comment] 2023-01-05 14:44
This is now fixed - see re-run CI of the last commit on main: https://github.com/LumiSpy/lumispy/runs/10461455605

**Closed by ericpre** 2023-01-05 14:44 UTC
Labels: type: bug
